[project]
name = "mytool"
version = "0.1.0"

[tool.pyside6-project]
files = [
    "main.py",
    "src/__init__.py",
    "src/app.py",
    "src/models/__init__.py",
    "src/models/file_time_tools.py",
    "src/models/git_tools.py",
    "src/models/qt_tools.py",
    "src/models/tool_manager.py",
    "src/models/windows_tools.py",
    "src/utils/__init__.py",
    "src/utils/config.py",
    "src/utils/logger.py",
    "src/resources/modify_file_time.ps1",
    "ui/Main.qml",
    "ui/theme/Theme.qml",
    "ui/components/ContentArea.qml",
    "ui/components/SidebarComponent.qml",
    "ui/components/SidebarItem.qml",
    "ui/components/TabBarComponent.qml",
    "ui/components/ToolBarComponent.qml",
    "ui/pages/AllToolsPage.qml",
    "ui/pages/FileTimeToolPage.qml",
    "ui/pages/GitToolPage.qml",
    "ui/pages/ProfilePage.qml",
    "ui/pages/QtToolPage.qml",
    "ui/pages/SettingsPage.qml",
    "ui/pages/WindowsToolPage.qml",
]
